"""Round-by-round hypotheses for the situational idea search.

Imported by scripts/pickem_idea_lab.py, which owns the data loading, the
holdout guard rail, the flipped-games evaluation and the multiplicity ledger.
Each round appends its experiments here so the whole search stays reproducible
and so PICKEM_MODEL.md's tables can be regenerated by one command.

Ideas come from a domain-expert agent that reads PICKEM_MODEL.md fresh each
round and is deliberately kept naive to the model's internals, so it proposes
football/market reasoning rather than variations on what already ships.
"""
from __future__ import annotations

import math

from edge.pickem import _coinflip_side, make_pick

MEAN_TOTAL = 44.0     # league-typical projected total, used as the centering point


def _shipped(g):
    return make_pick(g["away"], g["home"], g["pool_line"], g["live_line"],
                     g["total_open"], g["total_close"])


def _moved(g, floor=0.5):
    return abs(g["move"]) >= floor


def _dtotal(g):
    if g["total_open"] is None or g["total_close"] is None:
        return None
    return g["total_close"] - g["total_open"]


def _fade(g):
    """The opposite of whatever the shipped model would pick."""
    return "away" if _shipped(g).side == "home" else "home"


def _primetime(g):
    if g["weekday"] in ("Thursday", "Monday", "Saturday"):
        return True
    t = g["gametime"] or ""
    if g["weekday"] == "Sunday" and ":" in t:
        try:
            return int(t.split(":")[0]) >= 19
        except ValueError:
            return False
    return False


def _ols(ys, xcols):
    """Least squares with intercept, via normal equations. Returns [b0, b1, ...]."""
    n = len(ys)
    k = len(xcols) + 1
    X = [[1.0] + [c[i] for c in xcols] for i in range(n)]
    XtX = [[sum(X[i][a] * X[i][b] for i in range(n)) for b in range(k)] for a in range(k)]
    Xty = [sum(X[i][a] * ys[i] for i in range(n)) for a in range(k)]
    for c in range(k):                                   # gaussian elimination
        p = max(range(c, k), key=lambda r: abs(XtX[r][c]))
        XtX[c], XtX[p] = XtX[p], XtX[c]
        Xty[c], Xty[p] = Xty[p], Xty[c]
        if abs(XtX[c][c]) < 1e-12:
            return [0.0] * k
        for r in range(k):
            if r == c:
                continue
            f = XtX[r][c] / XtX[c][c]
            for cc in range(c, k):
                XtX[r][cc] -= f * XtX[c][cc]
            Xty[r] -= f * Xty[c]
    return [Xty[i] / XtX[i][i] for i in range(k)]


def _corr(a, b):
    n = len(a)
    if n < 3:
        return 0.0
    ma, mb = sum(a) / n, sum(b) / n
    num = sum((x - ma) * (y - mb) for x, y in zip(a, b))
    da = math.sqrt(sum((x - ma) ** 2 for x in a))
    db = math.sqrt(sum((y - mb) ** 2 for y in b))
    return num / (da * db) if da and db else 0.0


def _split(rows, TRAIN):
    return ([g for g in rows if g["season"] in TRAIN],
            [g for g in rows if g["season"] not in TRAIN])


# ============================================================== SANITY ======

def sanity(rows, ledger, evaluate, report, header):
    """Harness self-tests. Not hypotheses -- never registered in the ledger."""
    header("HARNESS SANITY CHECKS (not registered as hypotheses)")
    report(evaluate(rows, "null rule (always defer to shipped)", lambda g: None),
           ledger, register=False)
    report(evaluate(rows, "inverted shipped (should be strongly negative)", _fade),
           ledger, register=False)
    report(evaluate(rows, "placebo (parity of len(home team code))",
                    lambda g: ("home" if len(g["home"]) % 2 == 0 else "away")
                    if _shipped(g).tier == "COIN FLIP" else None),
           ledger, register=False)


# ============================================================== ROUND 1 =====

def round1(rows, ledger, evaluate, report, header):
    TRAIN = set(range(2014, 2020))
    tr, va = _split(rows, TRAIN)

    header("ROUND 1 -- KILL TESTS (single regressions, run before any pick machinery)")

    # --- K1: does the spread scale with the scoring environment? -----------
    print("\n  K1. Does true margin scale with the projected total?")
    print("      regress margin ~ pool_line + pool_line*(total_open - 44), TRAIN only")
    for lab, sub in (("TRAIN", tr), ("VALIDATE", va)):
        d = [g for g in sub if g["total_open"] is not None]
        ys = [g["margin"] for g in d]
        x1 = [g["pool_line"] for g in d]
        x2 = [g["pool_line"] * (g["total_open"] - MEAN_TOTAL) for g in d]
        b = _ols(ys, [x1, x2])
        # beta expressed per point of total, relative to the main line coefficient
        rel = b[2] / b[1] if b[1] else 0.0
        print(f"      [{lab:<8}] b_line={b[1]:+.4f}  b_interaction={b[2]:+.5f}  "
              f"implied beta={rel:+.5f} per pt of total")

    # --- K2: does the market move the SPREAD for wind, or only the TOTAL? --
    print("\n  K2. Wind: does the market move the total for it (yes?) and the spread (no?)")
    out = [g for g in rows if g["outdoor"] and g["wind"] is not None
           and g["total_open"] is not None and g["total_close"] is not None]
    print(f"      outdoor dev games with wind recorded: {len(out)}")
    print(f"      corr(wind, total_close-total_open) = "
          f"{_corr([g['wind'] for g in out], [_dtotal(g) for g in out]):+.3f}   "
          f"(expect NEGATIVE if the market learns wind in-week)")
    print(f"      corr(wind, |spread move|)          = "
          f"{_corr([g['wind'] for g in out], [abs(g['move']) for g in out]):+.3f}")
    print(f"      corr(wind, signed move toward dog) = "
          f"{_corr([g['wind'] for g in out], [g['move'] if g['pool_line'] < 0 else -g['move'] for g in out]):+.3f}")
    print("      mean |total move| by wind bucket:")
    for lo, hi in ((0, 9), (9, 13), (13, 18), (18, 99)):
        s = [g for g in out if lo <= g["wind"] < hi]
        if not s:
            continue
        print(f"        wind {lo:>2}-{hi:<3} n={len(s):4d}  "
              f"mean dtotal {sum(_dtotal(g) for g in s)/len(s):+5.2f}  "
              f"dog cover vs frozen "
              f"{sum(1 for g in s if g['home_covers'] is not None and ((g['pool_line']>0)==g['home_covers']))/max(1,sum(1 for g in s if g['home_covers'] is not None)):5.1%}")
    print("      DOME PLACEBO (must be flat -- these games have no wind):")
    dome = [g for g in rows if not g["outdoor"] and g["total_open"] is not None]
    dw = sum(1 for g in dome if g["home_covers"] is not None
             and ((g["pool_line"] > 0) == g["home_covers"]))
    dn = sum(1 for g in dome if g["home_covers"] is not None)
    print(f"        dome/closed n={dn}  dog cover {dw/dn:.1%}")

    header("ROUND 1 -- PICK-RULE TESTS (each registered in the multiplicity ledger)")

    # --- 1. Total-corroboration gate ---------------------------------------
    print("\n  Idea 1: fade the spread move when the TOTAL did not corroborate it.")
    print("  (info moves are subtractive -> total falls; money moves leave the total alone)")
    for lo, hi, lab in ((1.0, 99.0, "total ROSE >=1.0 (money move -> fade)"),
                        (-99.0, -1.0, "total FELL >=1.0 (info move -> follow, control)")):
        d = [g for g in rows if _moved(g) and _dtotal(g) is not None
             and lo <= _dtotal(g) < hi and g["home_covers"] is not None]
        w = sum(1 for g in d if (_shipped(g).side == "home") == g["home_covers"])
        print(f"    descriptive: {lab:<45} shipped goes {w}-{len(d)-w} "
              f"({w/len(d):.1%}, n={len(d)})")

    report(evaluate(rows, "R1.1 fade move when total ROSE >=1.0",
                    lambda g: _fade(g) if (_moved(g) and _dtotal(g) is not None
                                           and _dtotal(g) >= 1.0) else None,
                    round_no=1), ledger)

    # --- 2. Scoring-environment scaling of the frozen line ------------------
    print("\n  Idea 2: scale the frozen spread by the projected scoring environment.")
    d = [g for g in tr if g["total_open"] is not None]
    b = _ols([g["margin"] for g in d], [[g["pool_line"] for g in d],
             [g["pool_line"] * (g["total_open"] - MEAN_TOTAL) for g in d]])
    beta = (b[2] / b[1]) if b[1] else 0.0
    beta_used = beta / 2                    # 5d: halve any dev-fitted magnitude
    print(f"    beta fitted on TRAIN = {beta:+.5f}/pt; applying halved {beta_used:+.5f}")

    def env_side(g):
        if g["total_open"] is None:
            return None
        env_edge = g["pool_line"] * beta_used * (g["total_open"] - MEAN_TOTAL)
        combined = g["move"] + env_edge
        if abs(combined) < 0.5:
            return None
        return "home" if combined < 0 else "away"

    report(evaluate(rows, "R1.2 environment-scaled line (total_open)", env_side,
                    round_no=1, notes=f"beta={beta_used:+.5f} halved from train"), ledger)

    # --- 3. Wind helps the underdog ----------------------------------------
    print("\n  Idea 3: high wind -> low scoring -> compressed margin -> underdog.")
    for thr in (13, 15):
        report(evaluate(rows, f"R1.3 outdoor wind>={thr} -> take the underdog",
                        lambda g, t=thr: (("home" if g["pool_line"] > 0 else "away")
                                          if (g["outdoor"] and g["wind"] is not None
                                              and g["wind"] >= t) else None),
                        round_no=1), ledger)

    # --- 4. Primetime shading ----------------------------------------------
    print("\n  Idea 4: fade small primetime moves toward the favourite (public shading).")

    def toward_fav(g):
        return (g["live_line"] < 0 and g["move"] < 0) or (g["live_line"] > 0 and g["move"] > 0)

    def pt_rule(g):
        return (_fade(g) if (_primetime(g) and _moved(g) and abs(g["move"]) <= 1.5
                             and toward_fav(g)) else None)

    report(evaluate(rows, "R1.4 fade small primetime moves toward favourite",
                    pt_rule, round_no=1), ledger)
    print("    CONTROL -- identical rule on 1pm Sunday games (no shading mechanism;")
    print("    if this fires too, the effect belongs to move size, not primetime):")
    report(evaluate(rows, "R1.4c CONTROL same rule on 1pm Sunday games",
                    lambda g: (_fade(g) if (not _primetime(g) and g["weekday"] == "Sunday"
                                            and _moved(g) and abs(g["move"]) <= 1.5
                                            and toward_fav(g)) else None),
                    round_no=1), ledger)

    # --- 5. Backup-QB over-adjustment --------------------------------------
    print("\n  Idea 5: does the market over-adjust when a starting QB is ruled out?")
    prev_qb = {}
    qb_change = {}
    for g in sorted(rows, key=lambda g: (g["season"], g["week"])):
        for side in ("home", "away"):
            team = g[side]
            qb = g[f"{side}_qb"]
            k = (g["season"], team)
            if k in prev_qb and qb and prev_qb[k] and qb != prev_qb[k]:
                qb_change[(g["season"], g["week"], team)] = True
            if qb:
                prev_qb[k] = qb

    def qb_lost(g, side):
        return qb_change.get((g["season"], g["week"], g[side]), False)

    n_ch = sum(1 for g in rows if qb_lost(g, "home") or qb_lost(g, "away"))
    print(f"    QB differs from that team's previous game: {n_ch} dev games "
          f"({16*n_ch/len(rows):.1f}/week)")

    def qb_rule(g):
        # market moved >=2 pts AWAY from the team with the new QB -> take that team
        if qb_lost(g, "home") and not qb_lost(g, "away") and g["move"] >= 2.0:
            return "home"
        if qb_lost(g, "away") and not qb_lost(g, "home") and g["move"] <= -2.0:
            return "away"
        return None

    report(evaluate(rows, "R1.5 back the team whose QB changed when line moved >=2 vs them",
                    qb_rule, round_no=1), ledger)

    # --- 6. Divisional rematch after a blowout ------------------------------
    print("\n  Idea 6: divisional rematch after a lopsided first meeting.")
    first = {}
    for g in sorted(rows, key=lambda g: (g["season"], g["week"])):
        key = (g["season"], frozenset((g["home"], g["away"])))
        if key not in first:
            first[key] = g

    def rematch_rule(g):
        if not g["div_game"]:
            return None
        key = (g["season"], frozenset((g["home"], g["away"])))
        m1 = first.get(key)
        if m1 is None or m1 is g or m1["week"] >= g["week"]:
            return None
        if abs(m1["margin"]) < 14:
            return None
        winner = m1["home"] if m1["margin"] > 0 else m1["away"]
        loser = m1["away"] if m1["margin"] > 0 else m1["home"]
        if g["home"] == loser:
            return "home"
        if g["away"] == loser:
            return "away"
        return None

    report(evaluate(rows, "R1.6 divisional rematch: back meeting-1 blowout LOSER",
                    rematch_rule, round_no=1), ledger)
    print("    CONTROL -- same rule where meeting 1 was decided by <7 (should be nothing):")

    def rematch_control(g):
        if not g["div_game"]:
            return None
        key = (g["season"], frozenset((g["home"], g["away"])))
        m1 = first.get(key)
        if m1 is None or m1 is g or m1["week"] >= g["week"] or abs(m1["margin"]) >= 7:
            return None
        loser = m1["away"] if m1["margin"] > 0 else m1["home"]
        return "home" if g["home"] == loser else ("away" if g["away"] == loser else None)

    report(evaluate(rows, "R1.6c CONTROL rematch after a CLOSE first meeting",
                    rematch_control, round_no=1), ledger)

    # R1.6 was consistently NEGATIVE in both eras (z=-2.02/-2.06, 0/9 seasons),
    # which is itself a directional claim: the inverse should then be positive.
    # Pre-registered follow-up rather than a fishing expedition -- a reliably
    # wrong rule and a reliably right one are the same finding with a sign.
    print("\n    INVERSE of R1.6 -- back the meeting-1 blowout WINNER instead:")

    def rematch_winner(g):
        if not g["div_game"]:
            return None
        key = (g["season"], frozenset((g["home"], g["away"])))
        m1 = first.get(key)
        if m1 is None or m1 is g or m1["week"] >= g["week"] or abs(m1["margin"]) < 14:
            return None
        winner = m1["home"] if m1["margin"] > 0 else m1["away"]
        return "home" if g["home"] == winner else ("away" if g["away"] == winner else None)

    report(evaluate(rows, "R1.6i INVERSE: back meeting-1 blowout WINNER",
                    rematch_winner, round_no=1), ledger)


# ============================================================== ROUND 2 =====

def _keyzone(g):
    """True if a key number (3 or 7, either sign) lies in or on the move's span."""
    lo, hi = min(g["pool_line"], g["live_line"]), max(g["pool_line"], g["live_line"])
    return any(lo <= k <= hi for k in (3.0, 7.0, -3.0, -7.0))


def _tiebreak_side(g):
    """What the shipped totals-drift tiebreak would say, ignoring the move."""
    return _coinflip_side(g["live_line"], g["total_open"], g["total_close"])


def _window(g):
    if g["weekday"] != "Sunday":
        return "non-Sunday"
    t = g["gametime"] or ""
    try:
        h = int(t.split(":")[0])
    except (ValueError, IndexError):
        return "unknown"
    return "Sun-early" if h < 16 else "Sun-late"


def round2(rows, ledger, evaluate, report, header):
    TRAIN = set(range(2014, 2020))

    header("ROUND 2 -- the half-point zone, the deadline, and the tiebreak's holes")

    n = len(rows)
    half = [g for g in rows if abs(g["move"]) == 0.5]
    flat = [g for g in rows if abs(g["move"]) < 0.5]
    print(f"\n  Exposure reframing: |move|=0.5 -> {len(half)} games ({16*len(half)/n:.2f}/wk); "
          f"|move|<0.5 -> {len(flat)} ({16*len(flat)/n:.2f}/wk)")
    print(f"  Combined {100*(len(half)+len(flat))/n:.1f}% of the slate has <=0.5 pts of signal.")

    # --- 1. Is a half-point move information, or vig management? -----------
    print("\n  Idea 1: treat |move|=0.5 as NO signal; route it to the totals tiebreak.")
    for lab, sel in (("|move|=0.5", lambda g: abs(g["move"]) == 0.5),
                     ("|move|=1.0", lambda g: abs(g["move"]) == 1.0),
                     ("|move|>=1.5", lambda g: abs(g["move"]) >= 1.5)):
        d = [g for g in rows if sel(g) and g["home_covers"] is not None]
        w = sum(1 for g in d if (_shipped(g).side == "home") == g["home_covers"])
        print(f"    descriptive: following the move on {lab:<12} "
              f"{w}-{len(d)-w} ({w/len(d):.1%}, n={len(d)})")

    report(evaluate(rows, "R2.1 route |move|=0.5 to the totals tiebreak",
                    lambda g: _tiebreak_side(g) if abs(g["move"]) == 0.5 else None,
                    round_no=2), ledger)

    report(evaluate(rows, "R2.1b same, only FLAT-ZONE halves (no key number in span)",
                    lambda g: (_tiebreak_side(g) if (abs(g["move"]) == 0.5
                                                     and not _keyzone(g)) else None),
                    round_no=2), ledger)

    print("    CONTROL -- route 1.0-pt moves to the tiebreak too. If this ALSO helps,")
    print("    the finding is 'the tiebreak beats small moves generally', not a")
    print("    half-point quantum effect:")
    report(evaluate(rows, "R2.1c CONTROL route |move|=1.0 to the tiebreak",
                    lambda g: _tiebreak_side(g) if abs(g["move"]) == 1.0 else None,
                    round_no=2), ledger)

    # --- 2. The 2x2 of spread direction x total direction -------------------
    print("\n  Idea 2: 2x2 grid -- spread move direction x total move direction.")
    print("  (recreational money takes the favourite AND the over on the same game)")

    def cell(g):
        if abs(g["move"]) < 0.5 or _dtotal(g) is None:
            return None
        to_fav = ((g["live_line"] < 0 and g["move"] < 0)
                  or (g["live_line"] > 0 and g["move"] > 0))
        dt = _dtotal(g)
        if abs(dt) < 0.5:
            return None
        return ("toFAV" if to_fav else "toDOG") + ("_totUP" if dt > 0 else "_totDN")

    for c in ("toFAV_totUP", "toFAV_totDN", "toDOG_totUP", "toDOG_totDN"):
        line = f"    {c:<12}"
        for lab, seas in (("train", TRAIN), ("val", None)):
            d = [g for g in rows if cell(g) == c and g["home_covers"] is not None
                 and ((g["season"] in TRAIN) if seas else (g["season"] not in TRAIN))]
            w = sum(1 for g in d if (_shipped(g).side == "home") == g["home_covers"])
            line += f"  {lab} {w/len(d):5.1%} (n={len(d):3d})" if d else f"  {lab} n/a"
        print(line)
    report(evaluate(rows, "R2.2 fade the toFAV_totUP cell (max-recreational signature)",
                    lambda g: _fade(g) if cell(g) == "toFAV_totUP" else None,
                    round_no=2), ledger)

    # --- 3. The deadline is not the close -----------------------------------
    print("\n  Idea 3: the pick deadline is each day's first kickoff, NOT the close.")
    print("  If late-window games win more at matched move size, that surplus is")
    print("  post-deadline information we will NOT have live.")
    for wlab in ("Sun-early", "Sun-late", "non-Sunday"):
        line = f"    {wlab:<11}"
        for mlab, msel in (("coinflip", lambda g: abs(g["move"]) < 0.5),
                           ("0.5-1.5", lambda g: 0.5 <= abs(g["move"]) <= 1.5),
                           ("2.0+", lambda g: abs(g["move"]) >= 2.0)):
            d = [g for g in rows if _window(g) == wlab and msel(g)
                 and g["home_covers"] is not None]
            w = sum(1 for g in d if (_shipped(g).side == "home") == g["home_covers"])
            line += f"  {mlab} {w/len(d):5.1%} (n={len(d):4d})" if d else f"  {mlab} n/a"
        print(line)
    print("    ^ the coin-flip column is the CONTROL: no movement signal exists there,")
    print("      so any window gap in it is a scheduling artifact (NFL flexes good games")
    print("      late) and must be subtracted before reading the moving columns.")

    report(evaluate(rows, "R2.3 raise threshold to 1.5 on Sunday-late games",
                    lambda g: (_tiebreak_side(g) if (_window(g) == "Sun-late"
                                                     and 0.5 <= abs(g["move"]) < 1.5)
                               else None), round_no=2), ledger)

    # --- 4. Fade small moves toward a team off a blowout win ----------------
    print("\n  Idea 4: fade small moves toward a team coming off a blowout WIN.")
    prev_margin = {}
    for g in sorted(rows, key=lambda g: (g["season"], g["week"])):
        g["_home_prev"] = prev_margin.get((g["season"], g["home"]))
        g["_away_prev"] = prev_margin.get((g["season"], g["away"]))
        prev_margin[(g["season"], g["home"])] = g["margin"]
        prev_margin[(g["season"], g["away"])] = -g["margin"]

    def blowout_rule(g, thr=14, lo=0.5, hi=1.0, sign=1):
        if not (lo <= abs(g["move"]) <= hi):
            return None
        toward = "home" if g["move"] < 0 else "away"
        prev = g["_home_prev"] if toward == "home" else g["_away_prev"]
        if prev is None or sign * prev < thr:
            return None
        return "away" if toward == "home" else "home"

    for thr in (14, 17, 21):
        report(evaluate(rows, f"R2.4 fade small move toward team off a >={thr} win",
                        lambda g, t=thr: blowout_rule(g, t), round_no=2), ledger)
    print("    CONTROL (a) symmetry -- same rule toward a team off a >=14 LOSS:")
    report(evaluate(rows, "R2.4a CONTROL toward team off a >=14 LOSS",
                    lambda g: blowout_rule(g, 14, sign=-1), round_no=2), ledger)
    print("    CONTROL (b) magnitude -- same rule on LARGE moves (>=2), which should")
    print("    be news-driven and immune:")
    report(evaluate(rows, "R2.4b CONTROL same rule on |move|>=2",
                    lambda g: blowout_rule(g, 14, lo=2.0, hi=99.0), round_no=2), ledger)

    # --- 5a. The tiebreak's fall-through -----------------------------------
    print("\n  Idea 5a: when spread AND total are both flat, the model falls through to")
    print("  'take the market favourite' -- the rule this doc measures at 48.3% on dev.")
    ft = [g for g in rows if abs(g["move"]) < 0.5 and _dtotal(g) is not None
          and abs(_dtotal(g)) < 0.5]
    print(f"    fall-through games: {len(ft)} ({16*len(ft)/n:.2f}/wk)")
    report(evaluate(rows, "R2.5a fall-through -> take the underdog instead",
                    lambda g: (("home" if g["pool_line"] > 0 else "away")
                               if (abs(g["move"]) < 0.5 and _dtotal(g) is not None
                                   and abs(_dtotal(g)) < 0.5) else None),
                    round_no=2), ledger)

    # --- 5b. Referee crew home-lean ----------------------------------------
    print("\n  Idea 5b: referee crew home-lean, as-of-week, heavily shrunk, coin flips only.")
    crew = {}
    leans = {}
    for g in sorted(rows, key=lambda g: (g["season"], g["week"])):
        r = g["referee"]
        if r:
            w, nn = crew.get(r, (0, 0))
            leans[id(g)] = (w - nn / 2) / (nn + 50) if nn else 0.0   # shrunk toward 0
            if g["home_covers"] is not None:
                crew[r] = (w + (1 if g["home_covers"] else 0), nn + 1)
        else:
            leans[id(g)] = 0.0

    def ref_rule(g):
        if _shipped(g).tier != "COIN FLIP":
            return None
        lean = leans.get(id(g), 0.0)
        if abs(lean) < 0.02:
            return None
        return "home" if lean > 0 else "away"

    report(evaluate(rows, "R2.5b referee crew home-lean on coin flips", ref_rule,
                    round_no=2), ledger)


# ============================================================== ROUND 3 =====

def round3(rows, ledger, evaluate, report, header):
    TRAIN = set(range(2014, 2020))

    header("ROUND 3 -- is drift front-loaded? (the calibration question)")

    # --- D1. movement vs elapsed time --------------------------------------
    print("\n  D1. If drift accumulated like a random walk, a Monday game (7 days from")
    print("      the opener) should move ~1.08x a Sunday game and Thursday ~0.76x.")
    print("      The backtest's 'frozen' line is a Sunday/Monday OPENER, but CBS")
    print("      freezes TUESDAY -- so front-loaded drift means CBS has already")
    print("      absorbed much of what the backtest credits to staleness.")
    for wd, days in (("Thursday", 3), ("Sunday", 6), ("Monday", 7)):
        d = [g for g in rows if g["weekday"] == wd]
        if not d:
            continue
        mv = sum(abs(g["move"]) for g in d) / len(d)
        dt = [abs(_dtotal(g)) for g in d if _dtotal(g) is not None]
        print(f"      {wd:<9} ~{days}d  n={len(d):4d}  mean |move| {mv:.3f}  "
              f"mean |dtotal| {sum(dt)/len(dt):.3f}")
    base = [g for g in rows if g["weekday"] == "Sunday"]
    bmv = sum(abs(g["move"]) for g in base) / len(base)
    for wd, days in (("Thursday", 3), ("Monday", 7)):
        d = [g for g in rows if g["weekday"] == wd]
        mv = sum(abs(g["move"]) for g in d) / len(d)
        print(f"      {wd:<9} observed/Sunday = {mv/bmv:.3f}   "
              f"random-walk expectation = {(days/6)**0.5:.3f}")

    # --- D2. is a point of movement worth the same at every window? --------
    print("\n  D2. Value per point of movement, by kickoff day and move size.")
    print("      If short-window (Thursday) points are worth MORE, the early")
    print("      correction is the valuable part and CBS's Tuesday post eats it.")
    for wd in ("Thursday", "Sunday", "Monday"):
        line = f"      {wd:<9}"
        for lab, sel in (("flat", lambda g: abs(g["move"]) < 0.5),
                         ("0.5-1.5", lambda g: 0.5 <= abs(g["move"]) <= 1.5),
                         ("2.0+", lambda g: abs(g["move"]) >= 2.0)):
            d = [g for g in rows if g["weekday"] == wd and sel(g)
                 and g["home_covers"] is not None]
            if not d:
                line += f"  {lab} n/a"
                continue
            w = sum(1 for g in d if (_shipped(g).side == "home") == g["home_covers"])
            line += f"  {lab} {w/len(d):5.1%} (n={len(d):4d})"
        print(line)

    print("\n  D3. Round 2(d) re-examined BY ERA -- the late-kickoff gap I reported")
    print("      pooled. Splitting it is the project's own standard and I skipped it.")
    for wlab in ("Sun-early", "Sun-late"):
        line = f"      {wlab:<10}"
        for elab, esel in (("train", lambda g: g["season"] in TRAIN),
                           ("val", lambda g: g["season"] not in TRAIN)):
            d = [g for g in rows if _window(g) == wlab and abs(g["move"]) >= 2.0
                 and esel(g) and g["home_covers"] is not None]
            w = sum(1 for g in d if (_shipped(g).side == "home") == g["home_covers"])
            line += f"  {elab} {w/len(d):5.1%} (n={len(d):3d})" if d else f"  {elab} n/a"
        print(line)

    header("ROUND 3 -- PICK-RULE TESTS")

    # --- 4. Never lay the hook over a key number on a small move -----------
    print("\n  Idea 4: at a frozen line of 3.5/7.5 with a small move, take the points.")
    print("  (5g dismissed 'capture' as downstream of the pick; defined UPSTREAM as")
    print("   'prefer the side holding the key when the signal is weak' it IS a")
    print("   side-changer, so 5g's structural objection does not apply.)")

    def hook_rule(g, keys=(3.5, 7.5), lo=0.0, hi=1.0):
        if abs(g["pool_line"]) not in keys or abs(g["move"]) > hi or abs(g["move"]) < lo:
            return None
        return "home" if g["pool_line"] > 0 else "away"      # the side getting points

    report(evaluate(rows, "R3.4 frozen 3.5/7.5 + small move -> take the points",
                    hook_rule, round_no=3), ledger)
    print("    CONTROL (a) MIRROR -- a real lumpiness effect must be symmetric:")
    report(evaluate(rows, "R3.4a CONTROL frozen 2.5/6.5 -> take the FAVOURITE",
                    lambda g: (("away" if g["pool_line"] > 0 else "home")
                               if (abs(g["pool_line"]) in (2.5, 6.5)
                                   and abs(g["move"]) <= 1.0) else None),
                    round_no=3), ledger)
    print("    CONTROL (b) PLACEBO -- same shape on non-key lines (4.5/8.5):")
    report(evaluate(rows, "R3.4b PLACEBO frozen 4.5/8.5 -> take the points",
                    lambda g: hook_rule(g, keys=(4.5, 8.5)), round_no=3), ledger)

    # --- 5. Divisional: confirm it is confidence, not a side --------------
    print("\n  Idea 5: divisional games are the most stable subgroup in the project.")
    for lab, seas in (("train", TRAIN), ("val", None)):
        for div in (True, False):
            d = [g for g in rows if g["div_game"] == div and g["home_covers"] is not None
                 and ((g["season"] in TRAIN) if seas else (g["season"] not in TRAIN))]
            w = sum(1 for g in d if (_shipped(g).side == "home") == g["home_covers"])
            print(f"      {lab:<6} {'divisional' if div else 'non-div':<11} "
                  f"{w/len(d):5.1%} (n={len(d)})")
    print("    per-season divisional win rate (stability check):")
    for s in sorted({g["season"] for g in rows}):
        d = [g for g in rows if g["season"] == s and g["div_game"]
             and g["home_covers"] is not None]
        w = sum(1 for g in d if (_shipped(g).side == "home") == g["home_covers"])
        print(f"      {s}  {w/len(d):5.1%} (n={len(d)})")
    print("    but is there a SIDE to take? (both should lose -- 5e's trap):")
    report(evaluate(rows, "R3.5 divisional -> take the underdog",
                    lambda g: (("home" if g["pool_line"] > 0 else "away")
                               if g["div_game"] else None), round_no=3), ledger)
    report(evaluate(rows, "R3.5b divisional -> take the road team",
                    lambda g: "away" if g["div_game"] else None, round_no=3), ledger)


# ============================================================== ROUND 4 =====

def round4(rows, ledger, evaluate, report, header):
    """The tournament question: is the pool a prediction task or a rank task?

    NOT agent-scouted -- the round-4 scout was cut off by an API spend limit,
    so this pursues the fully-specified thread left by round 3's scout rather
    than substituting a less-independent idea generator. Flagged because the
    value of rounds 1-3 came from the scout being NAIVE to this model, and
    that property is absent here.

    THE CONFOUND THAT HAD TO BE REMOVED (kept as a comment because it is the
    kind of mistake that looks like a result): simulating with the REAL
    flat-zone outcomes credits each policy with whatever that policy happened
    to score on dev. The shipped tiebreak went 57.3% train / 49.0% validate --
    a sign flip, i.e. noise -- but pooled to 54.4%, so the simulation handed
    it a spurious win-rate advantage and the shadow benefit appeared to
    REVERSE at reduced edge. Randomising flat-zone outcomes to true coin
    flips gives all policies identical expected wins, leaving correlation
    with the field as the only difference. That is the effect being measured.
    """
    import numpy as np

    TRAIN = set(range(2014, 2020))
    header("ROUND 4 -- the pool is a TOURNAMENT: are coin-flip picks free?")

    live = [g for g in rows if g["home_covers"] is not None]
    flat = [g for g in live if _shipped(g).tier == "COIN FLIP"]

    print("\n  A. Flat-zone EV with a confidence interval. If it brackets 50%, those")
    print("     ~3 picks/week are FREE and can be spent on rank instead of on wins.")
    for lab, sel in (("TRAIN", lambda g: g["season"] in TRAIN),
                     ("VALIDATE", lambda g: g["season"] not in TRAIN),
                     ("DEV pooled", lambda g: True)):
        d = [g for g in flat if sel(g)]
        w = sum(1 for g in d if (_shipped(g).side == "home") == g["home_covers"])
        n = len(d); p = w / n; se = (0.25 / n) ** 0.5
        print(f"     {lab:<11} {w}-{n-w}  {p:.1%}  "
              f"95% CI [{p-1.96*se:.1%}, {p+1.96*se:.1%}]  n={n}")
    for lab, fn in (("always favourite", lambda g: "away" if g["pool_line"] > 0 else "home"),
                    ("always underdog", lambda g: "home" if g["pool_line"] > 0 else "away")):
        line = f"     {lab:<18}"
        for elab, sel in (("train", lambda g: g["season"] in TRAIN),
                          ("val", lambda g: g["season"] not in TRAIN)):
            d = [g for g in flat if sel(g)]
            w = sum(1 for g in d if (fn(g) == "home") == g["home_covers"])
            line += f"  {elab} {w/len(d):5.1%} (n={len(d)})"
        print(line)
    print("     ^ all three sign-flip between eras. Flat-zone EV is 50%.")

    by_season = {}
    for g in live:
        by_season.setdefault(g["season"], []).append(g)
    S = []
    for _, games in sorted(by_season.items()):
        sig = np.array([_shipped(g).tier != "COIN FLIP" for g in games])
        ok = np.array([(_shipped(g).side == "home") == g["home_covers"] for g in games])
        fc = np.array([(("away" if g["pool_line"] > 0 else "home") == "home")
                       == g["home_covers"] for g in games])
        S.append((sig, ok, fc))

    def sim(top, edge_scale, lo, hi, n_sim=20000, n_opp=17, seed=11):
        rng = np.random.default_rng(seed)
        out = {p: [] for p in ("current", "shadow", "diverge")}
        for sig, ok_sig, favc in S:
            nflat = int((~sig).sum()); n_sig = int(sig.sum())
            f_sig = int(favc[sig].sum())
            nr = int(ok_sig[sig].sum()); nw = n_sig - nr
            keep = edge_scale + (1 - edge_scale) * 0.5
            truth = rng.random((n_sim, nflat)) < 0.5     # flat games: fresh coin flips
            lean = rng.uniform(lo, hi, size=(n_sim, n_opp))
            opp = rng.binomial(f_sig, lean) + rng.binomial(n_sig - f_sig, 1 - lean)
            for i in range(n_opp):
                opp[:, i] += ((rng.random((n_sim, nflat)) < lean[:, i][:, None])
                              == truth).sum(axis=1)
            my_sig = (rng.binomial(nr, keep, size=n_sim)
                      + rng.binomial(nw, (1 - edge_scale) * 0.5, size=n_sim))
            for p in out:
                if p == "shadow":
                    mf = truth.sum(axis=1)
                elif p == "diverge":
                    mf = (~truth).sum(axis=1)
                else:
                    mf = ((rng.random((n_sim, nflat)) < 0.5) == truth).sum(axis=1)
                my = my_sig + mf
                out[p].append(((1 + (opp > my[:, None]).sum(axis=1)) <= top).mean())
        return {p: float(np.mean(v)) for p, v in out.items()}

    print("\n  B. PURE tournament effect -- flat-zone outcomes randomised to true coin")
    print("     flips, so all policies have identical expected WINS and differ only in")
    print("     correlation with the field. P(top 4 of 18), 20k sims/season.")
    print(f"\n     {'field':<22} {'edge':<6} {'current':>8} {'shadow':>8} "
          f"{'diverge':>8} {'shadow-current':>16}")
    for flab, (lo, hi) in (("weak (lean .55-.90)", (0.55, 0.90)),
                           ("realistic (.70-.95)", (0.70, 0.95)),
                           ("sharp (.85-1.00)", (0.85, 1.00))):
        for elab, es in (("full", 1.0), ("60%", 0.6), ("30%", 0.3)):
            r = sim(4, es, lo, hi)
            print(f"     {flab:<22} {elab:<6} {r['current']:>7.1%} {r['shadow']:>8.1%} "
                  f"{r['diverge']:>8.1%} {100*(r['shadow']-r['current']):>+15.2f}pp")
    print("     ^ shadow wins in EVERY cell with a real edge, and the advantage GROWS")
    print("       as the field gets sharper -- the signature of a correlation effect.")

    print("\n  B2. Adam CANNOT see his pool's picks pre-lock (confirmed 2026-08-23), so")
    print("      the strategy must run on CBS's NATIONAL percentage. Does that cost much?")
    print("      oracle = shadow the realised 18-person majority (impossible in practice)")
    print("      prior  = shadow the a-priori popular side (what he can actually do)")

    def sim2(edge_scale, lo, hi, n_sim=20000, n_opp=17, top=4, seed=13):
        rng = np.random.default_rng(seed)
        out = {p: [] for p in ("current", "prior", "oracle")}
        for sig, ok_sig, favc in S:
            nflat = int((~sig).sum()); n_sig = int(sig.sum())
            f_sig = int(favc[sig].sum())
            nr = int(ok_sig[sig].sum()); nw = n_sig - nr
            keep = edge_scale + (1 - edge_scale) * 0.5
            truth = rng.random((n_sim, nflat)) < 0.5
            lean = rng.uniform(lo, hi, size=(n_sim, n_opp))
            opp = rng.binomial(f_sig, lean) + rng.binomial(n_sig - f_sig, 1 - lean)
            took = np.empty((n_sim, n_opp, nflat), dtype=bool)
            for i in range(n_opp):
                took[:, i, :] = rng.random((n_sim, nflat)) < lean[:, i][:, None]
                opp[:, i] += (took[:, i, :] == truth).sum(axis=1)
            majority = took.sum(axis=1) > (n_opp / 2)
            my_sig = (rng.binomial(nr, keep, size=n_sim)
                      + rng.binomial(nw, (1 - edge_scale) * 0.5, size=n_sim))
            for p in out:
                if p == "prior":
                    mf = truth.sum(axis=1)
                elif p == "oracle":
                    mf = (majority == truth).sum(axis=1)
                else:
                    mf = ((rng.random((n_sim, nflat)) < 0.5) == truth).sum(axis=1)
                my = my_sig + mf
                out[p].append(((1 + (opp > my[:, None]).sum(axis=1)) <= top).mean())
        return {p: float(np.mean(v)) for p, v in out.items()}

    print(f"\n      {'field':<22} {'edge':<6} {'current':>8} {'prior':>8} {'oracle':>8} "
          f"{'prior captures':>16}")
    for flab, (lo, hi) in (("weak (.55-.90)", (0.55, 0.90)),
                           ("realistic (.70-.95)", (0.70, 0.95)),
                           ("sharp (.85-1.00)", (0.85, 1.00))):
        for elab, es in (("full", 1.0), ("60%", 0.6)):
            r = sim2(es, lo, hi)
            go = r["oracle"] - r["current"]; gp = r["prior"] - r["current"]
            frac = (gp / go * 100) if abs(go) > 1e-9 else float("nan")
            print(f"      {flab:<22} {elab:<6} {r['current']:>7.1%} {r['prior']:>8.1%} "
                  f"{r['oracle']:>8.1%} {frac:>15.0f}%")
    print("      ^ 96-100%. With 18 opponents who lean the same way, the realised")
    print("        majority IS the popular side, so observing it adds ~nothing.")

    print("\n  C. Does it flip for a winner-take-all prize? (realistic field, full edge)")
    print(f"     {'prize shape':<26} {'current':>8} {'shadow':>8} {'diverge':>8}   best")
    for top, lab in ((1, "1st only (weekly prize)"), (2, "top 2"),
                     (4, "top 4 (season money)"), (8, "top 8 (beat the median)")):
        r = sim(top, 1.0, 0.70, 0.95)
        print(f"     {lab:<26} {r['current']:>7.1%} {r['shadow']:>8.1%} "
              f"{r['diverge']:>8.1%}   {max(r, key=r.get)}")
    print("     ^ does NOT flip, but the edge shrinks as the target narrows. Correct:")
    print("       variance-seeking is for UNDERDOGS, and this model is the field's")
    print("       favourite. Section 7's chase mode covers the behind-late case.")


# ============================================================== ROUND 5 =====

def round5(rows, ledger, evaluate, report, header):
    """Score the tournament in DOLLARS, not P(top 4) -- round 4's objective was
    misspecified, and the weekly winner-take-all pot pulls the opposite way.

    Agent-scouted. The scout's DIRECTION was right (weekly prize favours
    variance, so shadowing costs money there) but its arithmetic understated
    the season side: it assumed shadowing only buys marginal 4th-place slots
    worth $150, when in fact protecting an edge lifts the whole ladder
    including the $1,200 top rung.
    """
    import numpy as np

    header("ROUND 5 -- score it in DOLLARS ($1200/450/300/150 + $50/week)")

    def fav(g):
        return "away" if g["pool_line"] > 0 else "home"

    live = [g for g in rows if g["home_covers"] is not None]

    # --- measured facts that recalibrate round 4 ---------------------------
    agree = sum(1 for g in live if _shipped(g).side == fav(g)) / len(live)
    wk = {}
    for g in live:
        wk.setdefault((g["season"], g["week"]), []).append(g)
    D = [sum(1 for g in gs if _shipped(g).side != fav(g)) for gs in wk.values()]
    print(f"\n  Model agrees with chalk on only {agree:.1%} of games. It already")
    print(f"  diverges from the favourite on {np.mean(D):.2f} games/week "
          f"(SD {np.std(D, ddof=1):.2f}, range {min(D)}-{max(D)}).")
    print("  So the 3 flat-zone picks round 4 tuned are a trim tab on a much bigger,")
    print("  uncontrolled budget -- which shrinks how much that tuning can matter.")

    # weekly outcome clustering: is there any to exploit?
    counts = [sum(1 for g in gs if (fav(g) == "home") == g["home_covers"]) for gs in wk.values()]
    ns = [len(gs) for gs in wk.values()]
    pbar = sum(counts) / sum(ns)
    chi = sum((c - n * pbar) ** 2 / (n * pbar * (1 - pbar)) for c, n in zip(counts, ns))
    df = len(counts) - 1
    print(f"\n  Weekly overdispersion check: chi2={chi:.1f} on df={df}, ratio "
          f"{chi/df:.3f} (z={(chi-df)/math.sqrt(2*df):+.2f}).")
    print("  Weekly ATS outcomes are NOT overdispersed -- there is no chalk-week")
    print("  clustering to buy variance from. Kills the correlate-your-divergences family.")

    # --- the dollar simulator ----------------------------------------------
    SE = []
    for season in sorted({g["season"] for g in live}):
        gs = [g for g in live if g["season"] == season]
        SE.append(dict(
            n=len(gs),
            widx=[np.array([i for i, g in enumerate(gs) if g["week"] == w])
                  for w in sorted({g["week"] for g in gs})],
            sig=np.array([_shipped(g).tier != "COIN FLIP" for g in gs]),
            favc=np.array([(fav(g) == "home") == g["home_covers"] for g in gs]),
            okm=np.array([(_shipped(g).side == "home") == g["home_covers"] for g in gs]),
            absl=np.array([abs(g["pool_line"]) for g in gs])))
    LADDER = {1: 1200.0, 2: 450.0, 3: 300.0, 4: 150.0}

    def sim(policy, beta, alo, ahi, edge=1.0, zero=False, n_sim=4000, n_opp=17, seed=5):
        rng = np.random.default_rng(seed)
        ts, tw = [], []
        for S in SE:
            n, sig = S["n"], S["sig"]
            nflat = int((~sig).sum())
            truth = S["favc"][None, :].repeat(n_sim, 0).copy()
            truth[:, ~sig] = rng.random((n_sim, nflat)) < 0.5
            alpha = rng.uniform(alo, ahi, size=(n_sim, n_opp))
            q = 1 / (1 + np.exp(-(alpha[:, :, None] + beta * S["absl"][None, None, :])))
            opp = (rng.random((n_sim, n_opp, n)) < q) == truth[:, None, :]
            my = np.empty((n_sim, n), dtype=bool)
            if zero:
                my[:] = rng.random((n_sim, n)) < 0.5
            else:
                so = S["okm"][None, :].repeat(n_sim, 0)
                if edge < 1.0:
                    deg = (rng.random((n_sim, n)) > edge) & sig[None, :]
                    so = np.where(deg, rng.random((n_sim, n)) < 0.5, so)
                my[:, sig] = so[:, sig]
                my[:, ~sig] = (truth[:, ~sig] if policy == "shadow" else
                               ~truth[:, ~sig] if policy == "diverge" else
                               (rng.random((n_sim, nflat)) < 0.5) == truth[:, ~sig])
            for idx in S["widx"]:
                ms = my[:, idx].sum(1)
                os_ = opp[:, :, idx].sum(2)
                nt = 1 + (os_ == ms[:, None]).sum(1)
                tw.append(np.where(ms > os_.max(1), 50.0,
                                   np.where(ms == os_.max(1), 50.0 / nt, 0.0)).mean())
            rank = 1 + (opp.sum(2) > my.sum(1)[:, None]).sum(1)
            ts.append(np.array([LADDER.get(int(r), 0.0) for r in rank]).mean())
        return float(np.sum(ts) / len(SE)), float(np.sum(tw) / len(SE))

    print("\n  Flat-zone outcomes randomised -> identical expected WINS for every policy.")
    print("  beta = how sharply opponents favour chalk as the spread grows (0 = round 4).")
    print(f"\n    {'field':<20} {'beta':<5} {'policy':<8} {'season$':>8} "
          f"{'weekly$':>8} {'TOTAL$':>8} {'vs cur':>8}")
    for flab, (alo, ahi) in (("chalky", (1.4, 2.9)), ("mixed", (0.4, 1.7))):
        for beta in (0.0, 0.2):
            base = None
            for pol in ("current", "shadow", "diverge"):
                sdol, wdol = sim(pol, beta, alo, ahi)
                t = sdol + wdol
                if pol == "current":
                    base = t
                print(f"    {flab:<20} {beta:<5} {pol:<8} {sdol:>8.0f} {wdol:>8.0f} "
                      f"{t:>8.0f} {'' if pol == 'current' else f'{t-base:>+7.0f}'}")
            print()

    print("    CONTROL -- Adam a pure coin flipper. All policies MUST converge:")
    for pol in ("current", "shadow", "diverge"):
        sdol, wdol = sim(pol, 0.2, 1.4, 2.9, zero=True)
        print(f"      {pol:<8} total ${sdol+wdol:>6.0f}")

    print("\n    Edge-survival sensitivity (chalky, beta=0.2). Round 3(a) says the")
    print("    live edge is probably BELOW backtested, so this row decides it:")
    print(f"      {'edge':<6} {'policy':<8} {'TOTAL$':>8} {'vs cur':>8}")
    for elab, e in (("full", 1.0), ("60%", 0.6), ("30%", 0.3)):
        base = None
        for pol in ("current", "shadow", "diverge"):
            sdol, wdol = sim(pol, 0.2, 1.4, 2.9, edge=e)
            t = sdol + wdol
            if pol == "current":
                base = t
            print(f"      {elab:<6} {pol:<8} {t:>8.0f} "
                  f"{'' if pol == 'current' else f'{t-base:>+7.0f}'}")


# ============================================================== ROUND 7 =====

def round7(rows, ledger, evaluate, report, header):
    """Adam's question (2026-08-23): a spread is normally -110 each side, but if
    money leans one way the other side's price improves toward +105 to balance.
    Does that PRICE movement indicate who beats the spread?

    Data note, stated honestly: nflverse carries only the CLOSING spread price,
    so the open->close movement itself cannot be measured. What CAN be measured
    is the closing ASYMMETRY, which is the accumulated result of that movement --
    a price that drifted from -110 to -120 closes at -120. So this tests the net
    effect of exactly the mechanism described, just not its path.

    Why it matters beyond the question: 5f lists public-pick fading as blocked
    forever for want of historical pick distributions. The juice is a readout of
    where the money is, and it exists for 100% of games 2014-2024. This is the
    closest substitute that will ever be available.
    """
    header("ROUND 7 -- does the SPREAD PRICE (juice) say who covers?")

    live = [g for g in rows if g["home_covers"] is not None
            and g.get("p_home_juice") is not None]
    print(f"\n  dev games with spread juice: {len(live)}")
    ph = [g["p_home_juice"] for g in live]
    print(f"  de-vigged P(home covers) implied by price: mean {sum(ph)/len(ph):.4f}, "
          f"range {min(ph):.3f}-{max(ph):.3f}")
    print(f"  share priced ~evenly (0.49-0.51, i.e. -110/-110): "
          f"{sum(1 for x in ph if 0.49 <= x <= 0.51)/len(ph):.1%}")

    TRAIN = set(range(2014, 2020))
    print("\n  Home cover rate vs the FROZEN line, by how the price leans:")
    print(f"    {'price bucket':<24} {'TRAIN':>24} {'VALIDATE':>24}")
    for lo, hi in ((0.0, 0.47), (0.47, 0.49), (0.49, 0.51), (0.51, 0.53), (0.53, 1.0)):
        line = f"    p_home {lo:.2f}-{hi:.2f}        "
        for sel in (lambda g: g["season"] in TRAIN, lambda g: g["season"] not in TRAIN):
            sub = [g for g in live if lo <= g["p_home_juice"] < hi and sel(g)]
            if not sub:
                line += f"{'n/a':>24}"
                continue
            w = sum(1 for g in sub if g["home_covers"])
            n = len(sub)
            line += f"  {w/n:6.1%} (z={(w/n-0.5)/math.sqrt(0.25/n):+.2f}, n={n:4d})"
        print(line)
    print("    ^ an informative price would make this RISE monotonically.")

    xs = [g["p_home_juice"] for g in live]
    ys = [1.0 if g["home_covers"] else 0.0 for g in live]
    print(f"\n  corr(price-implied P(home), home actually covers) = {_corr(xs, ys):+.4f}")

    def juiced_side(g):
        """The side the money is on = the side priced worse (higher implied p)."""
        return "home" if g["p_home_juice"] > 0.5 else "away"

    def unjuiced_side(g):
        return "away" if g["p_home_juice"] > 0.5 else "home"

    print("\n  Side-changing rules -- the only thing that can add wins:")
    for thr in (0.505, 0.52):
        report(evaluate(rows, f"R7.1 coin flips -> FOLLOW the money (p>={thr})",
                        lambda g, t=thr: (juiced_side(g)
                                          if (g.get("p_home_juice") is not None
                                              and _shipped(g).tier == "COIN FLIP"
                                              and abs(g["p_home_juice"] - 0.5) >= t - 0.5)
                                          else None), round_no=7), ledger)
        report(evaluate(rows, f"R7.2 coin flips -> FADE the money (p>={thr})",
                        lambda g, t=thr: (unjuiced_side(g)
                                          if (g.get("p_home_juice") is not None
                                              and _shipped(g).tier == "COIN FLIP"
                                              and abs(g["p_home_juice"] - 0.5) >= t - 0.5)
                                          else None), round_no=7), ledger)
    report(evaluate(rows, "R7.3 full slate: override to the FADE side when price is extreme",
                    lambda g: (unjuiced_side(g)
                               if (g.get("p_home_juice") is not None
                                   and abs(g["p_home_juice"] - 0.5) >= 0.03) else None),
                    round_no=7), ledger)


def run_rounds(rows, ledger, evaluate, report, header):
    sanity(rows, ledger, evaluate, report, header)
    round1(rows, ledger, evaluate, report, header)
    round2(rows, ledger, evaluate, report, header)
    round3(rows, ledger, evaluate, report, header)
    round4(rows, ledger, evaluate, report, header)
    round5(rows, ledger, evaluate, report, header)
    round7(rows, ledger, evaluate, report, header)
